from subactions.action_check_person_name import ActionCheckPersonName
from mostra_documento import ActionMostraDocumento
from action_list_documents import ActionListAllDocuments
from elastic_actions import ActionSearchElasticsearch
# Qui potrai importare altre actions man mano che le crei
